#+TITLE: Prepatory Mathematics in the Age of Information
#+AUTHOR: teilchen010
#+EMAIL: teilchen010@gmail.com
# date ... will set (change) each time (if remembered)
#+DATE: [2015-10-06 Tue 14:32]
#+FILETAGS: :math:
#+LANGUAGE:  en
#+HTML_HEAD: <link rel="stylesheet" href="data/stylesheet.css" type="text/css">
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+HTML_MATHJAX: align: left indent: 5em tagside: left font: Neo-Euler font-size: 2.5em
#+LATEX_HEADER: \usepackage[makeroom]{cancel}
#+LATEX_CLASS: tuftehandout
#+OPTIONS: H:10 num:4 toc:t \n:nil @:t ::t |:t _:{} *:t ^:{} prop:t
#+OPTIONS: prop:t
#+OPTIONS: tex:t
#+STARTUP: showall
#+STARTUP: align
#+STARTUP: indent
#+STARTUP: entitiespretty
#+STARTUP: logdrawer
#+STARTUP: hidestars
#+STARTUP: latexpreview

#+begin_html
<script type="text/x-mathjax-config">
	  MathJax.Hub.Config({
	    TeX: {extensions: ["cancel.js"]},
	    tex2jax: {
	      inlineMath: [ ['$','$'], ['\\(','\\)'] ],
	      processEscapes: true
	    }
	  });
	</script>
#+end_html


#+BEGIN_abstract

#+END_abstract

* Introduction

Once upon a time the main customer of mathematics was the greater world of physics and engineering. While in today's world math is just as involved with physics and engineering as ever, we now find it necessary to broaden mathematics to include the world of computers and their unique approach to mathematics. Along with classic /[[https://en.wikipedia.org/wiki/Mathematical_analysis][continuous]]/ mathematics, computers have ushered in a new era of /[[https://en.wikipedia.org/wiki/Discrete_mathematics][discrete]]/ mathematics.

Roughly speaking, /continuous/ math is the math of things in motion, e.g., objects and their paths or trajectories, forces measured to the decimal place. In continuous math there is typically a /formula/. On the other hand, /discrete/ math deals with separate, /discrete/ entities, things are usually reoresented with integers, there are /systems/ of finite, non-smoothly associated objects.

/Discrete/ mathematics is largely absent from the secondary school curriculum, and, except for /[[https://en.wikipedia.org/wiki/Linear_algebra][linear algebra]]/, not emphasized in the first undergraduate years of college either. And yet theoretical computer science is all about discrete mathematics. An issue running parallel to the dearth of discrete math is the glaring absence of any cohesive approach to programming computers. Again, secondary education offers very little programming, and outside of computer science programs, college science curricula mostly follow a "catch as catch can" approach to learning to program. For example, when this author took numerical analysis from his math department, the professor offered no advice---let alone training---on how to do the programming assignments. Luckily, some of us stumbled onto [[https://en.wikipedia.org/wiki/Fortran][FORTRAN]] and hacked together our assignments, mostly by guesswork.

These deficiencies have been topics of discussion for many years. The first major breakthrough came in the mid 1980s from [[https://en.wikipedia.org/wiki/Gerald_Jay_Sussman][Gerald Sussman]] and [[https://en.wikipedia.org/wiki/Hal_Abelson][Hal Abelson]] at MIT with their landmark textbook [[https://en.wikipedia.org/wiki/Structure_and_Interpretation_of_Computer_Programs][Structure and Interpretation of Computer Programs]]. Its nickname was /the wizard book/ due to the wizardy-looking cartoon character on the cover. SICP served for many years as the text for their MIT Electrical Engineering and Computer Science course /6.001/. SICP was praised by critics as a nexus of computer theory and numerical application. However, its use of the [[https://en.wikipedia.org/wiki/Scheme_(programming_language)][Scheme]] programming language, as well as its legendary "hard math" practice exercises doomed acceptance beyond any but the top university computer science programs.

Today the importance of learning math on the computer cannot be emphasized enough, as nearly all real-world mathematics is done on computers. Gone are the days of slide rules, pocket calculators, log and trig tables, gone even are the days of mainframe computers chugging away in some remote clean room at FORTRAN numerical programs. Today's math is done as much on consumer-class computers with both free and commercial software, as on massively parallel super computers in clean rooms.

 This text aims to revolutionize the instruction of mathematics by including the computer and programming at each step. Math will be, first and foremost, in the context of the computer. /If you can code it, you own it/ might be our motto. And to /code it/ we'll be using the /SICP/ standby Scheme, specifically the /[[https://racket-lang.org/][Racket]]/ dialect. (See Appendix [] for installation instructions, and Appendix [] for some basic skill-building.)

* A cautionary tale

In regular math we see /functions/, expressions, equations. A function is a statement, an equation is a statement, a mathematical expression is also a statement of some mathematical relationship, hopefully accurate and true. Math builds, derives, juxtaposes functions, expressions, equations in order to get at some basic, fundamental truth of the matter at hand. With an equation like $y = y_0e^{kt}$ we see a /factory/ of sorts that takes a thing $y$, perhaps a bacteria blob, at an initial starting time $t = 0$, that is, it's state at $y_0$, and multiplies it by [[https://en.wikipedia.org/wiki/E_(mathematical_constant)][Euler's "magic" constant]] $e$ raised to the power of $kt$, where $t$ is time and $k$ is a constant, i.e., $e^{kt}$. What is this for? What does it do? Well, to begin answering this question many mathematics teachers would first want their students to know where the equation came from---maybe not the whole historical rendition of when and who plucked it out of the /mathematical void/---but students should see that it is /derived/ using valid, mathematically-legal substitutions and simplifications from a more basic mathematical statement

\begin{align*}
\frac{dy}{dt} = ky
\end{align*}

. . . then the students do some homework problems, and maybe see in on a test. And there the ball stops---until a day comes when one of them must use the /exponential rate of growth or decay dependent on initial size/ formula in a real-world setting---invariably on a computer; invariably in a much messier situation than the Calculus text problem set.

/Kathy/ is a new hire at a huge multi-national chemical engineering firm, and the last time she saw anything about exponential growth/decay was in her college Calculus course some four years ago. She only remembers plugging numbers into a hand calculator and writing down the answer on a test. But now her new boss wants her to do some growth factor calculations "/on the computer/". Not sure how to proceed, she asks around discreetly, to which someone says "/Oh, I think you could use/ Excel /for that sort of thing./"

Googling, she [[http://www.excelfunctions.net/Excel-Growth-Function.html][finds a page]] on an Excel exponential growth formula---but it's in some unfamiliar computer code, and, on top of that, it doesn't look the same as the formula she dimly recalls from college. But she's got a /good head for math/ and a strong desire to prove herself, so she keeps after it until something works and it looks right. She takes the printout to her boss . . . and he stares at it unsmiling, looking almost like he's been insulted. Finally he hands it back to her, saying "/Have Roy set you up a Matlab account/. Yes, sir. And so Roy, her unit's sysadmin, does so, but just as she begins to ask "/What do I do now?/" he hands her a five pound, two thousand-page Matlab manual. "/Study this/," he says, smirking, an eyebrow raised.

The afternoon passes as she wades through the book's intro and partly into the first chapter, playing around with the first examples on her new Matlab account. But during lunch in the cafeteria, she overhears a group of colleagues talking about /matrices/, then something called /Python/, then something called /Clojure/. She asks them to explain, and they say Matlab is good for some things, but their group is "writing applications." Oh.

Later as she's at a restaurant with her friends, as they're talking about something on /YouTube/, she sighs and wishes she had seen some of this /numerical/ stuff before being thrown into the shark tank. A bridge would have been nice between the world of school math---with theories and practice problems from textbooks worked out with pencil, paper, and calculator---and the proverbial deep end of the real world where everything seemed to revolve around computers and software. She realizes that she, with a good, solid Bachelors in math, must transform herself into a numerical analyst in no time flat.

Later, about two chapters into an online /Numerical Analysis/ textbook, she surmises the whole point is to find strategies to approximate the nice, clean math of textbooks, approximations that can then be done on computers. In effect, numerical methods are formulas to actually apply formulas. . .  

* /Pi/ from an algorithmic standpoint

. . .for example, Kathy found out /pi/, the ratio of a circle's circumference and its diameter, can be derived in many ways. And even before the dawn of computers, numerical methods were used to get at a real solution to the basic $\pi = \nicefrac{C}{d}$.


* A Warm-up: Prime Factorization For Unlike Denominators

Seriously large denominators require the /prime factoring/ method
in order to get like-denominators.

/Prime factorization/ means /factoring out/ the /prime numbers/ of a number. For example:
  
$18 = 2(9)$ or $18$ equals $2$ times $9$ (using Algebra notation for /times/)

but $9$ is not a prime number. So we must /factor/ it:

$9 = 3(3)$

Now we can say $18 = (2)(3)(3)$ (again, using Algebra notation for /times/) or, using /powers/, $18 = 2(3^2)$ where $3^2$ is the same as $3\cdot3$ or $3$ times $3$.

Before going any further, we should maybe talk about /prime numbers/ or just /primes/. A prime is simply a number that has no possible factorization other than $1$ and itself. So this table:
    
#+tblname: primes
| 2 | 3 | 5 | 7 | 11 | 13 | 17 | 19 | 23 | 29 | 31 | 37 | 41 | 43 | 47 | 53 | 59 | 61 | 67 | 71 | 73 | 79 | 83 | 89 | 97 | 101 | 103 | 107 | 109 |

shows the first $29$ primes. Again, nobody in this table is divisible by anything other than $1$ and that number itself; no other numbers will divide into a prime number.

 When you think of numbers in terms of primes, any number is just a bunch of primes multiplied together---sometimes repeatedly, e.g.,

    \begin{align*}
    38 & = (2)(18)\\
       & = (2)(2)(9)\\
       & = (2)(2)(3)(3)\\
    \end{align*}
    or
    \begin{align*}
    38 & = (2^2)(3^2)
    \end{align*}

    So the prime factors of $38$ are just the primes $2$ and $3$. We can now say the /factors of any number are just prime numbers/. Take a look at [[https://en.wikipedia.org/wiki/Table_of_prime_factors][this link]] for a tables of the first $1,000$ numbers as factors of primes.

** A bit of Algebra; Using /symbols/ for primes.

- If we match the primes to letters, like ~a, b, c~,

  #+tblname: prime_symbols
  | a | b | c | d |  e |  f |  g |  h |  i |
  |---+---+---+---+----+----+----+----+----|
  | 2 | 3 | 5 | 7 | 11 | 13 | 17 | 19 | 23 |

  we can write the denominators of fractions like this:

  \[
  \frac{1}{85} \equiv \frac{1}{(5)(17)} \equiv \frac{1}{cg}
  \]
  where $cg$ is (as above) $c$ times $g$. (\equiv means equivalent or "the same as") And for another fraction

  \[
  \frac{1}{276} \equiv \frac{1}{(2^2)(3)(23)} \equiv \frac{1}{a^2bi}
  \]

  As you can see, the /factors/ in the denominator of both fractions are made up entirely of primes. Now we can pick a combination of these primes to make a /lowest common denominator/, which is a fancy way of saying the smallest denominator that both original denominators are some multiple of.

  \[
  \frac{1}{85} + \frac{1}{276} \quad \textrm{or} \quad \frac{1}{cg} + \frac{1}{a^2bi}
  \]

  Broken down into their prime factors, we see that the two fractions have unique prime factors, i.e., they do not share any prime factors. This means a common denominator between the two must include /all/ the prime factors /and/ their powers:

  \[
  \frac{1}{cg} + \frac{1}{a^2bi} \equiv \frac{(1)(a^2bi) + (1)(cg)}{(cg)(a^2bi)}
  \]

  If we substitute the original numbers back in. . .

  \[
  \frac{(1)(2^2)(3)(23) + (1)(5)(17)}{(5)(17)(2^2)(3)(23)}
  \]

  By the way, this is the extreme condition where the common denominator cannot be anything less than simply multiplying the original denominators. Why? What happened? The two denominators---when factored down to their respective prime factors---had /nothing/, no primes, in commmon.

  But what do we do with the numerators? We're not allowed to change the value of the fractions in our attempt to add them---and we don't. And so we use an Algebra trick to keep the fractions the same value. The trick, of course, is multiplying something by $1$, which, of course, doesn't change it:

  \[
  \bigg(\frac{1}{85}\bigg)\bigg(\frac{276}{276}\bigg) + \bigg(\frac{1}{276}\bigg)\bigg(\frac{85}{85}\bigg) \quad \textrm{or} \quad  \bigg(\frac{1\cdot276}{85\cdot276}\bigg) + \bigg(\frac{1\cdot85}{276\cdot85}\bigg)
  \]

  then

  \[
  \frac{(1)(276) + (1)(85)}{(85)(276)} = \frac{276 + 85}{23460} = \frac{361}{23460}
  \]

  Let's look at something where the denominators might be large, but have more primes in common. How about

  \[
  \frac{1}{40} + \frac{1}{81} + \frac{1}{92} \quad \textrm{or} \quad \frac{1}{a^3c} + \frac{1}{b^4} + \frac{1}{a^2i} \quad \textrm{or} \quad \frac{1}{(2^3)(5)} + \frac{1}{3^4} + \frac{1}{(2^2)(23)} 
  \]

  here we see the primes $2$, $3$, $5$, and  $23$ in use. Now we need to establish what the /lowest common denominator/ (LCD) should be. The old /brute force/ method of finding an LCD would be to simply multiply all the denominators together ($40$ \cdot $81$ \cdot $92$) and then multiply the numerators by whatever was need to keep it honest. We, however, don't need such /mathématiques brutale/. We're clever enough to sense that if a prime in one denominator is also found in another denominator, /we can simply disregard the lesser power of that prime and use the greater power to build our LCD./ Our example has just such a situation. Notice above that we have the prime $2$ in both $\frac{1}{40}$ and in $\frac{1}{92}$. Notice also that $\frac{1}{40}$ has $2^3$ while $\frac{1}{92}$ has just $2^2$. The beauty of the *prime factorization* method is that we can throw out the lesser power (here $2^2$) and build our LCD out of the greater power $2^3$

  \[
  \frac{1}{(2^3)(5)} + \frac{1}{3^4} + \frac{1}{\cancel{(2^2)}(23)}
  \]

  so now our denominator will be made up what we might call the /significant/ or /principle/ primes: $(2^3)(3^4)(5)(23)$ or $74,520$. Still /ugly/-big, but smaller by the factor of $2^2$ we were able to drop, i.e., $74,520$ < $298,080$ by a /factor/ (note the common English use of /factor/) of $4$. Now, getting the numerators right will simply be the Algebra trick of multiplying each fraction by a version of $1$, i.e., not changing its actual value, but making each fraction have like-denominators so we may add them. Again, in order to transform $\frac{1}{40}$ into a version with our LCD $74,520$, then $\frac{1}{81}$, lastly, $\frac{1}{92}$, we multiply each by a different version of $1$, in the form of $\frac{a}{a}$ where $a$ is that number, which, when multiplied by the fraction's denominator, will give the LCD, in this case $74,520$:

  \[
  \bigg(\frac{(3^4)(23)}{(3^4)(23)}\bigg)\bigg(\frac{1}{40}\bigg) + \bigg(\frac{(2^3)(5)(23)}{(2^3)(5)(23)}\bigg)\bigg(\frac{1}{81}\bigg) + \bigg(\frac{(2)(3^4)(5)}{(2)(3^4)(5)}\bigg)\bigg(\frac{1}{92}\bigg)
  \]

  or

  \[
  \bigg(\frac{1863}{1863}\bigg)\bigg(\frac{1}{40}\bigg) + \bigg(\frac{920}{920}\bigg)\bigg(\frac{1}{81}\bigg) + \bigg(\frac{810}{810}\bigg)\bigg(\frac{1}{92}\bigg)
  \]

  or

  \[
  \frac{1863}{74520} + \frac{920}{74520} + \frac{810}{74520} = \frac{3593}{74520}
  \]

  Note, we multiply each fraction by the factors the fraction's denominator doesn't contain. So with $\frac{1}{92}$, which contributed $2^2$ and $23$ to the LCD, we make the $\frac{something}{something}$

  Another way to figure out the numerators---or what we should multiply each fraction's numerator by---is to simply divide the LCD by the original denominator, e.g., for $\frac{1}{40}$ we have $74,520 \div 40 = 1,863$, and yes, $1,863$ is the same answer as before, i.e., we multiply $\frac{1}{40}$ by $\frac{1863}{1863}$ to get $\frac{1}{40}$ represented in terms of our LCD.

  
