name:                omnimath
version:             0.1.0.0
github:              "borgauf/omnimath"
license:             BSD3
author:              "Lawrence Bottorff"
maintainer:          "borgauf@gmail.com"
copyright:           "2022 Lawrence Bottorff"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/borgauf/omnimath#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck 
- old-locale
- time
- mtl
- HUnit
- hmatrix
- Chart-diagrams
- algebraic-graphs
- linearEqSolver

library:
  source-dirs: src

executables:
  omnimath-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - omnimath

tests:
  omnimath-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - omnimath
